#!/usr/bin/env perl
use strict;
use warnings;
BEGIN {push @INC, '/mnt/Grishka/Projets/shell/bash-completer/lib'}

## Completion of perldealer
use BashCompleter;
BashCompleter::complete_options('-n', '--quantity', sub {
	print '1 5 10';
	return 1;
});
BashCompleter::complete_actions(sub {
	print "a b c d e";

	return 1;
});
BashCompleter::collect_options('-t', '--test');
BashCompleter::complete();

## Rest of the program
print "\ncontinuation of program\n";

use Getopt::Long;

my $quantity = 1;
GetOptions ("quantity=i" => \$quantity)   # flag
or die("Error in command line arguments\n");

print "I buy and sell perls.\n";

my $action = shift or die "Specify an action: 'buy' or 'sell'.";

if ($action eq 'buy') {
	print "There are your $quantity perls.\n";
} elsif ($action eq "sell") {
	print "Thanks for these $quantity perls.\n";
} else {
	print "Invalid action: 'buy' or 'sell'.\n";
}

exit 0;