#!/usr/bin/env python

import completer_util as cu
import os.path

def completeActions(stream):
  return 1, [ "greet", "share", "leave" ]

def completeRepetition(stream):
  if cu.isNewer(stream):
    return 0

  return 1, [ "random", "once", "few" ]

def completeName(stream):
  return 2, [ "brother", "man" ]

completer = cu.Completer()
completer.completeActions(completeActions)
completer.completeOptions(["-r", "--repeat"], completeRepetition)
completer.completeOptions(["-n", "--name"], completeName)
completer.doCompletion()

print "Hello man"