#!/usr/bin/env python

import completer_util
import os.path

def completeActions(stream):
  return 1, [ "greet", "share", "leave" ]

def completeRepetition(stream):
  if os.path.getmtime(stream) > os.path.getmtime(__file__):
    return 0

  return 1, [ "random", "once", "few" ]

def completeName(stream):
  return 2, [ "brother", "man" ]

completer = completer_util.Completer()

completer.completeActions(completeActions)
completer.completeOptions(["-r", "--repeat"], completeRepetition)
completer.completeOptions(["-n", "--name"], completeName)
completer.doCompletion()

print "Hello man"